# -*- coding: utf-8 -*-
"""data download and continuity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174n3DtbyBU6I0k2_hXslYaEvkPY9TUEH
"""

#Display files
import requests

dataset = "ds006110"
version = "1.2.1"

query = """
query getFiles($datasetId: ID!, $tag: String!, $tree: String) {
  snapshot(datasetId: $datasetId, tag: $tag) {
    files(tree: $tree) {
      id
      filename
      size
      directory
      urls
    }
  }
}
"""

def get_files(tree=None):
    resp = requests.post(
        "https://openneuro.org/crn/graphql",
        json={"query": query, "variables": {"datasetId": dataset, "tag": version, "tree": tree}},
    )
    data = resp.json()
    if "errors" in data:
        print("ERROR:", data["errors"])
        return []
    return data["data"]["snapshot"]["files"]

# Walk down: derivatives -> EEG -> cleaned_RELAX -> FieldTrip_format
path_parts = ["derivatives", "EEG", "cleaned_RELAX", "FieldTrip_format"]

current_files = get_files(tree=None)  # root
current_tree_id = None

for part in path_parts:
    match = next((f for f in current_files if f["filename"] == part and f["directory"]), None)
    if match is None:
        print(f"Could not find directory '{part}' at this level. Available entries:")
        for f in current_files:
            print(" -", f["filename"], "(dir)" if f["directory"] else "")
        break
    current_tree_id = match["id"]
    current_files = get_files(tree=current_tree_id)

else:
    # Successfully walked the whole path
    print(f"Found {len(current_files)} files in {'/'.join(path_parts)}\n")
    for f in current_files:
        print(f["filename"], "-", f["size"], "bytes")

total_bytes = df["size"].sum()
print(f"Total size: {total_bytes/1e9:.2f} GB across {len(df)} files")

#downloading data from openneuro
import requests
import zipfile
import os
from tqdm import tqdm

output_dir = "/content/FieldTrip_format_tmp"
zip_path = "/content/ds006110_FieldTrip_format.zip"
os.makedirs(output_dir, exist_ok=True)

session = requests.Session()

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_STORED) as zf:
    for _, row in tqdm(df.iterrows(), total=len(df), desc="Downloading + zipping"):
        filename = row["filename"]
        url = row["urls"][0]
        local_path = os.path.join(output_dir, filename)

        # Stream download to avoid loading whole file into memory
        with session.get(url, stream=True) as r:
            r.raise_for_status()
            with open(local_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=8 * 1024 * 1024):
                    f.write(chunk)

        # Add to zip, then remove the loose copy to save disk space
        zf.write(local_path, arcname=filename)
        os.remove(local_path)

os.rmdir(output_dir)
print(f"Done. Zip saved at: {zip_path}")
print(f"Zip size: {os.path.getsize(zip_path)/1e9:.2f} GB")

#Continuity Check
import requests
import re
import os
import scipy.io as sio
import numpy as np
import pandas as pd
from tqdm import tqdm

# ---- Step 1: Rebuild the file listing for FieldTrip_format ----
dataset = "ds006110"
version = "1.2.1"

query = """
query getFiles($datasetId: ID!, $tag: String!, $tree: String) {
  snapshot(datasetId: $datasetId, tag: $tag) {
    files(tree: $tree) {
      id
      filename
      size
      directory
      urls
    }
  }
}
"""

def get_files(tree=None):
    resp = requests.post(
        "https://openneuro.org/crn/graphql",
        json={"query": query, "variables": {"datasetId": dataset, "tag": version, "tree": tree}},
    )
    data = resp.json()
    if "errors" in data:
        print("ERROR:", data["errors"])
        return []
    return data["data"]["snapshot"]["files"]

path_parts = ["derivatives", "EEG", "cleaned_RELAX", "FieldTrip_format"]

current_files = get_files(tree=None)
for part in path_parts:
    match = next((f for f in current_files if f["filename"] == part and f["directory"]), None)
    if match is None:
        raise RuntimeError(f"Could not find directory '{part}'")
    current_files = get_files(tree=match["id"])

df = pd.DataFrame(current_files)[["filename", "size", "urls"]]
print(f"Found {len(df)} files in {'/'.join(path_parts)}")

# ---- Step 2: Check continuity of each file's time vector ----
filename_pattern = re.compile(
    r"sub-(?P<patient>PC\d+)_ses-(?P<session>\d+)_task-(?P<task>[a-zA-Z]+)_Clean-ft\.mat"
)

temp_path = "/content/temp_continuity_check.mat"
results = []
errors = []

for _, row in tqdm(df.iterrows(), total=len(df), desc="Checking continuity"):
    filename = row["filename"]
    m = filename_pattern.match(filename)
    if not m:
        errors.append((filename, "filename did not match expected pattern"))
        continue

    patient = m.group("patient")
    session = f"session {int(m.group('session'))}"
    context = m.group("task")

    try:
        with requests.get(row["urls"][0], stream=True) as r:
            r.raise_for_status()
            with open(temp_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=8 * 1024 * 1024):
                    f.write(chunk)

        mat = sio.loadmat(temp_path, squeeze_me=True, struct_as_record=False)
        ftData = mat["ftData"]
        fsample = float(ftData.fsample)
        time = ftData.time
        expected_step = 1.0 / fsample

        diffs = np.diff(time)
        tolerance = expected_step * 0.01  # allow 1% float rounding wiggle
        gap_mask = np.abs(diffs - expected_step) > tolerance
        n_gaps = int(gap_mask.sum())
        max_gap = float(diffs.max()) if len(diffs) else 0.0

        results.append({
            "patient": patient,
            "context": context,
            "session": session,
            "n_samples": len(time),
            "expected_step_sec": expected_step,
            "n_discontinuities": n_gaps,
            "max_gap_sec": round(max_gap, 4),
            "is_continuous": n_gaps == 0,
        })

    except Exception as e:
        errors.append((filename, str(e)))
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)

result_df = pd.DataFrame(results)
result_df.to_csv("/content/ds006110_continuity_check.csv", index=False)

print(f"\nDone. {len(results)} files checked, {len(errors)} errors.")
print(f"Files with discontinuities: {(~result_df['is_continuous']).sum()} / {len(result_df)}")
result_df[~result_df["is_continuous"]]