# -*- coding: utf-8 -*-
"""Psiconnect2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbh08yK-teDSdXDwAme_MBYg_L3DtqRk

Environment setup
"""

!pip install mne crosci -q

import os
import requests
import numpy as np
import scipy.io as sio
import mne
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap

from crosci.biomarkers import compute_band_biomarkers, compute_spectrum_biomarkers, get_frequency_bins

EHINGER_COLORS = [
    (0.2706, 0.4588, 0.7059),
    (0.5686, 0.7490, 0.8588),
    (0.8784, 0.9529, 0.9725),
    (1.0000, 1.0000, 0.7490),
    (0.9961, 0.8784, 0.5647),
    (0.9882, 0.5529, 0.3490),
    (0.8431, 0.1882, 0.1529),
]
cmap_becp = LinearSegmentedColormap.from_list("becp", EHINGER_COLORS, N=256)

"""Fetch OpenNeuro file listing"""

dataset = "ds006110"
version = "1.2.1"

query = """
query getFiles($datasetId: ID!, $tag: String!, $tree: String) {
  snapshot(datasetId: $datasetId, tag: $tag) {
    files(tree: $tree) {
      id
      filename
      size
      directory
      urls
    }
  }
}
"""

def get_files(tree=None):
    resp = requests.post(
        "https://openneuro.org/crn/graphql",
        json={"query": query, "variables": {"datasetId": dataset, "tag": version, "tree": tree}},
    )
    data = resp.json()
    if "errors" in data:
        print("ERROR:", data["errors"])
        return []
    return data["data"]["snapshot"]["files"]

path_parts = ["derivatives", "EEG", "cleaned_RELAX", "FieldTrip_format"]

current_files = get_files(tree=None)
for part in path_parts:
    match = next((f for f in current_files if f["filename"] == part and f["directory"]), None)
    if match is None:
        raise RuntimeError(f"Could not find directory '{part}'")
    current_files = get_files(tree=match["id"])

print(f"Found {len(current_files)} files in {'/'.join(path_parts)}")

"""Download PC001 resting-state files"""

SUBJECT = "PC001"
TARGET_FILES = {
    "pre":  f"sub-{SUBJECT}_ses-01_task-rest_Clean-ft.mat",
    "post": f"sub-{SUBJECT}_ses-02_task-rest_Clean-ft.mat",
}

DOWNLOAD_DIR = f"/content/{SUBJECT}_psilocybin"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

FPATHS = {}
for label, target in TARGET_FILES.items():
    entry = next((f for f in current_files if f["filename"] == target), None)
    if entry is None:
        raise FileNotFoundError(f"Could not find {target} in the OpenNeuro file listing")

    out_path = os.path.join(DOWNLOAD_DIR, target)
    print(f"Downloading {target} ...")
    with requests.get(entry["urls"][0], stream=True) as r:
        r.raise_for_status()
        with open(out_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8 * 1024 * 1024):
                f.write(chunk)

    FPATHS[label] = out_path

print(FPATHS)

"""Define frequency bands"""

CANONICAL_BANDS = {
    "delta": [1, 4],
    "theta": [4, 8],
    "alpha": [8, 13],
    "beta":  [13, 30],
    "gamma": [30, 45],
}
BROADBAND = [1, 45]

ALL_BANDS = {**CANONICAL_BANDS, "broadband": BROADBAND}
BAND_NAMES = list(ALL_BANDS.keys())
SPECTRUM_RANGE = [1, 45]  # used later for the fine-grained spectrum (Step 11)

"""Load and parse .mat files"""

def load_ft_mat(fpath):
    mat = sio.loadmat(fpath, squeeze_me=True, struct_as_record=False)
    ftData = mat["ftData"]

    fs = int(round(float(ftData.fsample)))   # crosci requires an int sampling rate
    chnames = list(ftData.label)
    signal = np.asarray(ftData.trial, dtype=float)   # (n_channels, n_times)
    if signal.dtype == object:
        signal = np.asarray(signal.item(), dtype=float)

    return signal, fs, chnames

"""Compute DFA and fE/I per band"""

def compute_metrics_allbands(fpath, bands=ALL_BANDS):
    signal, fs, chnames = load_ft_mat(fpath)
    n_channels, n_times = signal.shape
    print(f"  {n_channels} channels, {n_times} samples, fs={fs} Hz, "
          f"duration={n_times/fs:.1f}s")

    dfa_by_band = {}
    fei_by_band = {}

    for band_name, band_range in bands.items():
        print(f"    Band: {band_name} ({band_range[0]}-{band_range[1]} Hz)")
        try:
            band_biomarkers = compute_band_biomarkers(signal, fs, band_range)
            dfa_by_band[band_name] = np.atleast_1d(np.asarray(band_biomarkers["DFA"], dtype=float))
            fei_by_band[band_name] = np.atleast_1d(np.asarray(band_biomarkers["fEI"], dtype=float))
        except (IndexError, ValueError) as e:
            print(f"    WARNING: {band_name} ({band_range}) failed — {e}")
            print(f"    Filling with NaN for this band. Consider adjusting its range.")
            dfa_by_band[band_name] = np.full(n_channels, np.nan)
            fei_by_band[band_name] = np.full(n_channels, np.nan)

    return {
        "chnames": chnames,
        "fs": fs,
        "dfa": dfa_by_band,
        "fei": fei_by_band,
    }

"""Validate and consolidate results"""

results = {}
for label, fpath in FPATHS.items():
    print(f"\nProcessing {label} (psilocybin) — all bands ...")
    results[label] = compute_metrics_allbands(fpath)

assert results["pre"]["chnames"] == results["post"]["chnames"], \
    "Channel names differ between sessions — check montage/labels before plotting."

chnames = results["pre"]["chnames"]
fs = results["pre"]["fs"]
n_channels = len(chnames)
conditions = ["pre", "post"]

"""Build MNE montage/info object"""

info = mne.create_info(ch_names=chnames, sfreq=fs, ch_types="eeg")
montage = mne.channels.make_standard_montage("standard_1020")
info.set_montage(montage, on_missing="warn")

"""Topomap grid: per-band, pre vs post vs difference"""

def plot_metric_grid(metric_key, metric_label, cbar_label):
    n_bands = len(BAND_NAMES)
    fig, axes = plt.subplots(n_bands, 3, figsize=(12, 3.2 * n_bands))

    for row, band_name in enumerate(BAND_NAMES):
        v_pre = np.nan_to_num(results["pre"][metric_key][band_name],
                               nan=np.nanmean(results["pre"][metric_key][band_name]))
        v_post = np.nan_to_num(results["post"][metric_key][band_name],
                                nan=np.nanmean(results["post"][metric_key][band_name]))
        diff = v_post - v_pre

        vmin = min(v_pre.min(), v_post.min())
        vmax = max(v_pre.max(), v_post.max())
        vabs = np.max(np.abs(diff)) if np.any(np.isfinite(diff)) else 1

        ax = axes[row, 0]
        im1, _ = mne.viz.plot_topomap(v_pre, info, axes=ax, show=False,
                                       cmap=cmap_becp, vlim=(vmin, vmax))
        ax.set_ylabel(band_name, fontsize=11, fontweight="bold")
        if row == 0:
            ax.set_title("Pre", fontsize=12, fontweight="bold")
        fig.colorbar(im1, ax=ax, shrink=0.7, pad=0.03)

        ax = axes[row, 1]
        im2, _ = mne.viz.plot_topomap(v_post, info, axes=ax, show=False,
                                       cmap=cmap_becp, vlim=(vmin, vmax))
        if row == 0:
            ax.set_title("Post", fontsize=12, fontweight="bold")
        fig.colorbar(im2, ax=ax, shrink=0.7, pad=0.03)

        ax = axes[row, 2]
        im3, _ = mne.viz.plot_topomap(diff, info, axes=ax, show=False,
                                       cmap="RdBu_r", vlim=(-vabs, vabs))
        if row == 0:
            ax.set_title("Δ (Post − Pre)", fontsize=12, fontweight="bold")
        fig.colorbar(im3, ax=ax, shrink=0.7, pad=0.03)

        axes[row, 0].annotate(band_name.upper(), xy=(-0.25, 0.5),
                               xycoords="axes fraction", fontsize=11,
                               fontweight="bold", rotation=90, va="center", ha="center")

    fig.suptitle(f"Subject {SUBJECT} — {metric_label} — All Bands (Pre / Post / Difference)",
                 fontsize=15, fontweight="bold", y=1.0)
    fig.tight_layout()
    return fig

fig_dfa = plot_metric_grid("dfa", "DFA", "DFA exponent α")
fig_dfa.savefig(f"/content/{SUBJECT}_DFA_allbands_topogrid.png", dpi=150, bbox_inches="tight")
plt.show()

fig_fei = plot_metric_grid("fei", "fE/I", "fE/I")
fig_fei.savefig(f"/content/{SUBJECT}_fEI_allbands_topogrid.png", dpi=150, bbox_inches="tight")
plt.show()

# Compact difference-only row
def plot_difference_row(metric_key, metric_label, cbar_label):
    fig, axes = plt.subplots(1, len(BAND_NAMES), figsize=(3.2 * len(BAND_NAMES), 4))

    for col, band_name in enumerate(BAND_NAMES):
        v_pre = np.nan_to_num(results["pre"][metric_key][band_name],
                               nan=np.nanmean(results["pre"][metric_key][band_name]))
        v_post = np.nan_to_num(results["post"][metric_key][band_name],
                                nan=np.nanmean(results["post"][metric_key][band_name]))
        diff = v_post - v_pre
        vabs = np.max(np.abs(diff)) if np.any(np.isfinite(diff)) else 1

        ax = axes[col]
        im, _ = mne.viz.plot_topomap(diff, info, axes=ax, show=False,
                                      cmap="RdBu_r", vlim=(-vabs, vabs))
        ax.set_title(band_name, fontsize=11, fontweight="bold")
        fig.colorbar(im, ax=ax, shrink=0.65, pad=0.04, label=cbar_label)

    fig.suptitle(f"Subject {SUBJECT} — {metric_label} — Δ (Post − Pre) Across All Bands",
                 fontsize=14, fontweight="bold")
    fig.tight_layout()
    return fig

fig_dfa_diff = plot_difference_row("dfa", "DFA", "Δ DFA exponent")
fig_dfa_diff.savefig(f"/content/{SUBJECT}_DFA_difference_row.png", dpi=150, bbox_inches="tight")
plt.show()

fig_fei_diff = plot_difference_row("fei", "fE/I", "Δ fE/I")
fig_fei_diff.savefig(f"/content/{SUBJECT}_fEI_difference_row.png", dpi=150, bbox_inches="tight")
plt.show()

"""Channel × band heatmap"""

def plot_channel_band_heatmap(metric_key, metric_label, cbar_label, cmap="RdBu_r"):
    diff_matrix = np.zeros((n_channels, len(BAND_NAMES)))
    for col, band_name in enumerate(BAND_NAMES):
        v_pre = np.nan_to_num(results["pre"][metric_key][band_name],
                               nan=np.nanmean(results["pre"][metric_key][band_name]))
        v_post = np.nan_to_num(results["post"][metric_key][band_name],
                                nan=np.nanmean(results["post"][metric_key][band_name]))
        diff_matrix[:, col] = v_post - v_pre

    vabs = np.nanmax(np.abs(diff_matrix))

    fig, ax = plt.subplots(figsize=(1.4 * len(BAND_NAMES) + 2, 0.22 * n_channels + 2))
    im = ax.imshow(diff_matrix, cmap=cmap, vmin=-vabs, vmax=vabs, aspect="auto")

    ax.set_xticks(range(len(BAND_NAMES)))
    ax.set_xticklabels(BAND_NAMES, rotation=45, ha="right")
    ax.set_yticks(range(n_channels))
    ax.set_yticklabels(chnames, fontsize=7)
    ax.set_xlabel("Frequency band")
    ax.set_ylabel("Channel")
    ax.set_title(f"{metric_label} — Δ (Post − Pre), All Channels × All Bands", fontweight="bold")

    fig.colorbar(im, ax=ax, shrink=0.8, label=cbar_label)
    fig.tight_layout()
    return fig, diff_matrix

fig_dfa_heat, dfa_diff_matrix = plot_channel_band_heatmap("dfa", "DFA", "Δ DFA exponent")
fig_dfa_heat.savefig(f"/content/{SUBJECT}_DFA_channel_band_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

fig_fei_heat, fei_diff_matrix = plot_channel_band_heatmap("fei", "fE/I", "Δ fE/I")
fig_fei_heat.savefig(f"/content/{SUBJECT}_fEI_channel_band_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

"""Fine-grained frequency-resolved spectrum"""

def compute_spectrum_for_session(fpath, spectrum_range=SPECTRUM_RANGE):
    signal, fs, chnames = load_ft_mat(fpath)
    spectrum_biomarkers = compute_spectrum_biomarkers(signal, fs, spectrum_range)
    dfa_spec = np.atleast_2d(np.asarray(spectrum_biomarkers["DFA"], dtype=float))   # (n_channels, n_bins)
    fei_spec = np.atleast_2d(np.asarray(spectrum_biomarkers["fEI"], dtype=float))   # (n_channels, n_bins)
    return dfa_spec, fei_spec, chnames, fs

print("\nComputing fine-grained spectrum — pre ...")
dfa_spec_pre, fei_spec_pre, _, _ = compute_spectrum_for_session(FPATHS["pre"])

print("Computing fine-grained spectrum — post ...")
dfa_spec_post, fei_spec_post, _, _ = compute_spectrum_for_session(FPATHS["post"])

frequency_bins = get_frequency_bins(SPECTRUM_RANGE)
bin_centers = np.array([(lo + hi) / 2 for lo, hi in frequency_bins])
print(f"Number of frequency bins: {len(frequency_bins)}")

"""Spectrum plot: mean across channels, canonical bands shaded"""

def plot_spectrum_with_bands(dfa_spec_pre, dfa_spec_post, fei_spec_pre, fei_spec_post,
                               bin_centers, canonical_bands):
    fig, axes = plt.subplots(2, 1, figsize=(12, 9), sharex=True)

    band_colors = {
        "delta": "#B3CDE3", "theta": "#CCEBC5", "alpha": "#DECBE4",
        "beta": "#FED9A6", "gamma": "#FFFFCC",
    }

    for ax, spec_pre, spec_post, metric_name, ylabel in [
        (axes[0], dfa_spec_pre, dfa_spec_post, "DFA", "DFA exponent α"),
        (axes[1], fei_spec_pre, fei_spec_post, "fE/I", "fE/I"),
    ]:
        mean_pre = np.nanmean(spec_pre, axis=0)
        sem_pre = np.nanstd(spec_pre, axis=0) / np.sqrt(spec_pre.shape[0])
        mean_post = np.nanmean(spec_post, axis=0)
        sem_post = np.nanstd(spec_post, axis=0) / np.sqrt(spec_post.shape[0])

        for band_name, (lo, hi) in canonical_bands.items():
            ax.axvspan(lo, hi, color=band_colors.get(band_name, "#EEEEEE"), alpha=0.3, zorder=0)

        ax.plot(bin_centers, mean_pre, "-o", color="tab:blue", label="Pre", markersize=3)
        ax.fill_between(bin_centers, mean_pre - sem_pre, mean_pre + sem_pre, color="tab:blue", alpha=0.2)

        ax.plot(bin_centers, mean_post, "-o", color="tab:red", label="Post", markersize=3)
        ax.fill_between(bin_centers, mean_post - sem_post, mean_post + sem_post, color="tab:red", alpha=0.2)

        ax.set_ylabel(ylabel)
        ax.set_title(f"{metric_name} — Frequency-Resolved Spectrum (mean ± SEM across channels)")
        ax.legend()
        ax.grid(alpha=0.3)

    axes[-1].set_xlabel("Frequency (Hz)")
    fig.suptitle(f"Subject {SUBJECT} — Pre vs Post Psilocybin — Frequency-Resolved DFA & fE/I",
                 fontsize=14, fontweight="bold")
    fig.tight_layout()
    return fig

fig_spectrum = plot_spectrum_with_bands(
    dfa_spec_pre, dfa_spec_post, fei_spec_pre, fei_spec_post, bin_centers, CANONICAL_BANDS
)
fig_spectrum.savefig(f"/content/{SUBJECT}_spectrum_pre_post_meanchannels.png", dpi=150, bbox_inches="tight")
plt.show()

"""Summary"""

summary_rows = []
for cond in conditions:
    for band_name in BAND_NAMES:
        for ch_idx, ch in enumerate(chnames):
            summary_rows.append({
                "condition": cond,
                "band": band_name,
                "channel": ch,
                "DFA": results[cond]["dfa"][band_name][ch_idx],
                "fEI": results[cond]["fei"][band_name][ch_idx],
            })

summary_df = pd.DataFrame(summary_rows)
out_csv = f"/content/{SUBJECT}_pre_post_allbands_dfa_fei.csv"
summary_df.to_csv(out_csv, index=False)
print(f"\nSaved: {out_csv}")
print(summary_df.groupby(["condition", "band"])[["DFA", "fEI"]].mean())